### ISSUE TITLE
请问这个./run.sh 从何而来。源码与skynet是如何做的关联，完成编译。./run.sh 无法运行

### ISSUE THREAD

**Issue by Lixiaolonghh** [liuhaopen/SkynetMMO#2]

**Comment by liuhaopen** [comment]
工程的根目录里就有个 run.sh 文件，skynet 是框架，启动是靠它的，源码是根据 skynet 框架的规范写的 services，用的是 lua，不需要参与编译。skynet 编译部分参与下：https://github.com/liuhaopen/SkynetMMO 和 https://github.com/cloudwu/skynet 哈
